---
- name: Ensure that Docker is installed
  apt: name=docker state=present

#- name: Grab package
#  shell: wget -qO- https://experimental.docker.com/ | sh

- name: Restart Docker
  service: name=docker state=restarted
